name: 'GitHub Cross-Commit Action'
description: 'Cross commits files from the base repository to another repo.'

branding:
  icon: "git-commit"
  color: "blue"

inputs:
  source-folder:
    description: "Sub folder of the repository to copy"
    required: true
  destination-repository:
    description: "Repository to be commited to (e.g. `github.com/StirlingLabs/CrossCommitAction`), must be accessible via https."
    required: true
  destination-folder:
    description: "Sub folder of the repository to copy into"
    required: true
  destination-branch:
    description: "Branch of the destination repository to commit to"
    required: true
    default: "alpha"
  git-commit-message:
    description: "Custom commit message to use"
    default: ""
    required: false
  git-commit-sign-off:
    description: "Sign-off commit"
    default: "false"
    required: false
  authorized-user:
    description: "If a protected repo, the username of someone with commit permissions to the repo"
    default: ""
    required: false
  authorized-user-secret:
    description: "If a protected repo, a personal access token or secret for the user with commit permissions (enabling commit)"
    default: ""
    required: false
  exclude:
    description: "Optionally exclude some directories from being synced in both src and dst. The value is treated as column separated list, e.g. skip_dir_in_src:.git:skip_dir_in_dst"
    required: false
    default: ""

runs:
  using: "composite"
  steps: 
    - shell: bash
      run: ${{ github.action_path }}/action.sh
      env:
        SOURCE: ${{ inputs.source-folder }}
        REPO: ${{ inputs.destination-repository }}
        TARGET: ${{ inputs.destination-folder }}
        BRANCH: ${{ inputs.destination-branch }}
        GIT_COMMIT_MSG: ${{ inputs.git-commit-message }}
        GIT_COMMIT_SIGN_OFF: ${{ inputs.git-commit-sign-off }}
        USER: ${{ inputs.authorized-user }}
        USER_SECRET: ${{ inputs.authorized-user-secret }}
        EXCLUDES: ${{ inputs.exclude }}
        GITHUB_TOKEN: ${{ github.token }}
